- name: Create environment to deploy an ELB and EC2 machines from scratch
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
  
  tasks:
  - name: Create VPC in region {{ region }}
    ec2_vpc_net:
      name: "{{ vpc.name }}"
      cidr_block: "{{ vpc.cidr_block }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      tenancy: default
    register: __vpc_info
  
  - name: Create internet gateway
    ec2_vpc_igw:
      vpc_id: "{{ __vpc_info.vpc.id }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      tags:
        Name: "{{ igw.name }}"
      state: present
    register: __igw_info

  - name: Create subnet {{ subnet1.name }}
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ __vpc_info.vpc.id }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      cidr: "{{ subnet1.cidr }}"
      tags:
        Name: "{{ subnet1.name }}"
    register: __subnet1_info

  - name: Create subnet {{ subnet2.name }}
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ __vpc_info.vpc.id }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      cidr: "{{ subnet2.cidr }}"
      tags:
        Name: "{{ subnet2.name }}"
    register: __subnet2_info

  - name: Get route table info of {{ __vpc_info.vpc.id }}
    ec2_vpc_route_table_info:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      filters:
        vpc-id: "{{ __vpc_info.vpc.id}}"
    register: __route_table_info

  - name: Set up public subnet route table "{{ __route_table_info.route_tables[0].id}}"
    ec2_vpc_route_table:
      route_table_id: "{{ __route_table_info.route_tables[0].id}}"
      vpc_id: "{{ __vpc_info.vpc.id}}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      tags:
        Name: "{{ route_table.name }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ __igw_info.gateway_id }}"
    register: __route_table_info

  - name: Create security group {{ security_group.name }} 
    ec2_group:
      name: "{{ security_group.name }}"
      description: "{{ security_group.description }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ __vpc_info.vpc.id}}"
      rules:
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on ssh port
        - proto: tcp
          ports:
            - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on http port
      tags:
        Name: "{{ security_group.name }}"
    register: __security_group